name: "Genshin Impact Helper"
  on:
    schedule:
      - cron: "0 22 * * *"  # scheduled at 06:00 (UTC+8) everyday
    workflow_dispatch:
  env:
    TZ: 'Asia/Shanghai'
jobs: build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout master
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            # ref: master
        - name: Set up python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Random sleep
           if: github.event_name == 'schedule'
         run: sleep $(shuf -i 10-30 -n 1)
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
       - name: Run sign
         env:
           COOKIE_MIHOYOBBS: ${{ secrets.COOKIE_MIHOYOBBS }}
           COOKIE_HOYOLAB: ${{ secrets.COOKIE_HOYOLAB }}
           COOKIE_WEIBO: ${{ secrets.COOKIE_WEIBO }}
           WEIBO_INTL_AID: ${{ secrets.WEIBO_INTL_AID }}
           WEIBO_INTL_S: ${{ secrets.WEIBO_INTL_S }}
           COOKIE_KA: ${{ secrets.COOKIE_KA }}
           BARK_KEY: ${{ secrets.BARK_KEY }}
           BARK_SOUND: ${{ secrets.BARK_SOUND }}
           COOL_PUSH_SKEY: ${{ secrets.COOL_PUSH_SKEY }}
           COOL_PUSH_MODE: ${{ secrets.COOL_PUSH_MODE }}
           CUSTOM_NOTIFIER: ${{ secrets.CUSTOM_NOTIFIER }}
           DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
           DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
           IGOT_KEY: ${{ secrets.IGOT_KEY }}
           PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
           PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER }}
           SCKEY: ${{ secrets.SCKEY }}
           SCTKEY: ${{ secrets.SCTKEY }}
           TG_BOT_API: ${{ secrets.TG_BOT_API }}
           TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
           TG_USER_ID: ${{ secrets.TG_USER_ID }}
           WW_ID: ${{ secrets.WW_ID }}
           WW_APP_SECRET: ${{ secrets.WW_APP_SECRET }}
           WW_APP_USERID: ${{ secrets.WW_APP_USERID }}
           WW_APP_AGENTID: ${{ secrets.WW_APP_AGENTID }}
           WW_BOT_KEY: ${{ secrets.WW_BOT_KEY }}
         run: |
           python3 genshinhelper
